trigger: none

pool:
  name: LinuxPool

variables:
  imageRepository: dhanu0395/springboot
  tags: $(Build.BuildId)

stages:
  - stage: buildStage
    jobs:
      - job: buildJobs
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'DjAzureSPNConnection'
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - task: Docker@2
            inputs:
              containerRegistry: 'docker0395'
              repository: $(imageRepository)
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              tags: |
                $(tags)

          - script: |
              echo "Running container..."
              docker run -d -p 8090:8090 --name sboot-app $(imageRepository):$(tags)
              sleep 10
              docker ps


          
